export const dummySeedlets = [
  {
    id: "1",
    title: "AI Study Buddy",
    description:
      "An AI-powered tool to help students learn faster and stay organized.",
    tags: ["AI", "EdTech"],
    author: "@janedev",
    interests: 0,
    likes: 0,
    comments: 0,
    lookingFor: ["Frontend Dev", "UX Designer"],
  },
  {
    id: "2",
    title: "FinTrackr",
    description: "A mobile app for managing and visualizing personal finances.",
    tags: ["Fintech", "Mobile"],
    author: "@mikesoft",
    interests: 0,
    likes: 0,
    comments: 0,
    lookingFor: ["Backend Dev"],
  },
  {
    id: "3",
    title: "GreenCart",
    description:
      "A sustainable grocery delivery service focused on eco-friendly packaging and local produce.",
    tags: ["Sustainability", "E-commerce"],
    author: "@greenqueen",
    interests: 0,
    likes: 0,
    comments: 0,
    lookingFor: ["Product Designer", "Frontend Dev"],
  },
  {
    id: "4",
    title: "MindBloom",
    description:
      "A mental wellness app offering guided journaling, mood tracking, and affirmations.",
    tags: ["HealthTech", "Wellness"],
    author: "@drjames",
    interests: 0,
    likes: 0,
    comments: 0,
    lookingFor: ["Mobile Dev", "Content Creator"],
  },
  {
    id: "5",
    title: "SkillSwap",
    description:
      "A peer-to-peer platform where users exchange skills — learn design, teach coding.",
    tags: ["EdTech", "Community"],
    author: "@techsavvy",
    interests: 0,
    likes: 0,
    comments: 0,
    lookingFor: ["Fullstack Dev", "Community Manager"],
  },
  {
    id: "6",
    title: "TrackTribe",
    description:
      "A fitness social network where users track progress and join virtual challenges.",
    tags: ["Fitness", "Social"],
    author: "@fitken",
    interests: 0,
    likes: 0,
    comments: 0,
    lookingFor: ["Mobile Dev", "Backend Dev"],
  },
];
